stages:
  test:
    cmd: FAST=0 make test
    deps:
    - data/gt-tracking.json.gz
    - data/pred-detections.json.gz
    - sparrow_tracky/deepsort/tracker.py
    - sparrow_tracky/deepsort/tracker_test.py
    outs:
    - data/metrics.json
