stages:
  test:
    cmd: python data/evaluate.py
    deps:
      - data/gt-tracking.json.gz
      - data/pred-detections.json.gz
      - data/evaluate.py
    metrics:
      - data/metrics/bicycle.json:
          cache: false
      - data/metrics/car.json:
          cache: false
      - data/metrics/chair.json:
          cache: false
      - data/metrics/person.json:
          cache: false
