stages:
  test:
    cmd: python data/evaluate.py
    deps:
      - data/gt-tracking.json.gz
      - data/pred-detections.json.gz
      - data/evaluate.py
    metrics:
      - data/no-kalman-filter/bicycle.json:
          cache: false
      - data/no-kalman-filter/car.json:
          cache: false
      - data/no-kalman-filter/chair.json:
          cache: false
      - data/no-kalman-filter/person.json:
          cache: false
